//
//  HomePresenter.swift
//  MultiModuleRefactor
//
//  Created by Aung Ko Ko on 24/09/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Networking

protocol HomePresentationLogic {
    func presentStudentList(response: Home.Something.ViewModel)
    func presentError(err: ServiceError)
}

class HomePresenter: HomePresentationLogic {
    
    weak var viewController: HomeDisplayLogic?
    func presentStudentList(response: Home.Something.ViewModel) {
        viewController?.presentStudentList(response: response)
    }
    
    func presentError(err: ServiceError) {
        viewController?.presentError(err: err)
    }
}
