//
//  HomeWorker.swift
//  MultiModuleRefactor
//
//  Created by Aung Ko Ko on 24/09/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Networking

class HomeWorker: BaseNetworking {
    
    func fetchStudents(networkConfig: HomeNetworkConfiguration, completion: @escaping([StudentNetworkModel?]) -> Void, failure: @escaping(ServiceError) -> Void) {
        
        self.fetchData(configuration: networkConfig, responseType: BaseStrapiModel<BaseEntityModel<StudentNetworkModel>>.self) { result in
            switch result {
            case .success(let response):
                if let response = response.data {
                    completion(response.map({ $0.attributes ?? nil }))
                } else {
                    failure(ServiceError(issueCode: .CUSTOM_MES(message: "Empty Students")))
                }
            case .failure(let issueCode):
                failure(issueCode)
            }
        }
    }
}
